#if 0
set -xe
eval c++ -std=c++20 -shared -fPIC -g3 -Og -o libplutobook.so \
         -Iinclude -Isource -Isource/graphics -Isource/layout -Isource/resource \
         $0 $(pkg-config --cflags --libs cairo expat fontconfig harfbuzz)
exit 0
#endif
#include "source/counters.cpp"
#include "source/cssparser.cpp"
#include "source/cssrule.cpp"
#include "source/cssstylesheet.cpp"
#include "source/csstokenizer.cpp"
#include "source/document.cpp"
#include "source/globalstring.cpp"
#include "source/graphics/color.cpp"
#include "source/graphics/geometry.cpp"
#include "source/graphics/graphicscontext.cpp"
#include "source/graphics/textshape.cpp"
#include "source/htmldocument.cpp"
#include "source/htmlentityparser.cpp"
#include "source/htmlparser.cpp"
#include "source/htmltokenizer.cpp"
#include "source/layout/blockbox.cpp"
#include "source/layout/borderpainter.cpp"
#include "source/layout/box.cpp"
#include "source/layout/boxlayer.cpp"
#include "source/layout/boxstyle.cpp"
#include "source/layout/boxview.cpp"
#include "source/layout/flexiblebox.cpp"
#include "source/layout/inlinebox.cpp"
#include "source/layout/linebox.cpp"
#include "source/layout/linelayout.cpp"
#include "source/layout/listitembox.cpp"
#include "source/layout/pagebox.cpp"
#include "source/layout/pagebuilder.cpp"
#include "source/layout/replacedbox.cpp"
#include "source/layout/svgboxmodel.cpp"
#include "source/layout/svgcontainerbox.cpp"
#define paintTextDecorations paintTextDecorations2
#include "source/layout/svglinelayout.cpp"
#include "source/layout/svgreplacedbox.cpp"
#include "source/layout/svgresourcebox.cpp"
#include "source/layout/svgshapebox.cpp"
#include "source/layout/svgtextbox.cpp"
#include "source/layout/tablebox.cpp"
#include "source/layout/textbox.cpp"
#include "source/plutobook.cc"
#include "source/plutobook.cpp"
#include "source/resource/fontresource.cpp"
#include "source/resource/imageresource.cpp"
#include "source/resource/resource.cpp"
#include "source/resource/textresource.cpp"
#include "source/resource/url.cpp"
#include "source/svgdocument.cpp"
#include "source/svgproperty.cpp"
#include "source/textbreakiterator.cpp"
#include "source/xmldocument.cpp"
#include "source/xmlparser.cpp"
